name: Deploy to ECS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Build with Maven
      run: mvn clean package
      
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/x2q2w2d1
      
    - name: Build, tag, and push image to ECR
      run: |
        IMAGE_TAG=latest
        docker build -t dev-jenkins-repo .
        docker tag dev-jenkins-repo:latest public.ecr.aws/x2q2w2d1/dev-jenkins-repo:latest
        docker push public.ecr.aws/x2q2w2d1/dev-jenkins-repo:latest
